services:
  init-nginx:
    image: busybox
    volumes:
      - nginx-data:/data/www/
    command:  | 
      sh -c "
      echo '<h1>TP1!</h1>' > /index.html &&
      echo 'Build: '$(date) >> /index.html
      "

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - nginx-data:/data/www/
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      init-nginx:
        condition: service_completed_successfully

volumes:
  nginx-data: