# Note: Pour obtenir le mot de passe initial, 
# consulter les logs du conteneur qBittorrent.
# $ docker logs qbittorrent
#******** Information ********
# To control qBittorrent, access the WebUI at: http://localhost:8080
# The WebUI administrator username is: admin
# The WebUI administrator password was not set. 
# A temporary password is provided for this session: QMdGVy98I
# You should set your own password in program preferences.
# Voir: Préférences -> Web UI -> Mot de passe
# Et redémmarer le conteneur après avoir changé le mot de passe.
# --------------------------------------------------------------

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ../volumes/qbittorrent-data/appdata:/config
    ports:
      - ${QBITTORRENT_PORT}:8080
    restart: unless-stopped

